[package]
name = "runstrate"
version = "0.0.1"
description = "Fast way to test a Substrate Runtime via RPC."
authors = ["Artur Gontijo <https://github.com/arturgontijo>"]
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/arturgontijo/runstrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "runstrate"

[dependencies]
anyhow = "1"
jsonrpsee = { version = "0.16.2", features = ["server", "client", "macros"] }
hex = { version = "0.4.3", default-features = false }

futures = { version = "0.3.21" }
tokio = { version = "1.16", features = ["full"] }

serde = "1.0.136"
serde_json = "1.0.85"

rand = "0.8"

codec = { package = "parity-scale-codec", version = "3.2.2" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-state-machine = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sc-client-api = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

# Pallets
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
pallet-template = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

# Runtime
# kusama-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "pallet-balances/std",
    "pallet-transaction-payment/std",
    "pallet-sudo/std",
    "pallet-template/std",
#    "kusama-runtime/std",
]
